/** AUTO-GENERATED by scripts/sync-app-config.mjs — do not edit manually */
export const bakedAppConfig = {
  "supabaseUrl": "https://pdsjvcgkuolgckrxhcgj.supabase.co",
  "supabaseAnonKey": "sb_publishable_hZrXgNXjkQqJMI8Z3T-rjQ_HQlrCKVo",
  "defaultAIModel": "qwen"
} as const;
